- hosts: localhost
  tasks:

    - name: Install vim
      apt: name=vim state=present
      become: yes
      tags: php

    - name: Install PHP
      apt: name=php state=present
      become: yes
      register: php_installed
      tags: php

    - name: Install PHP-CURL
      apt: name=php7.0-curl state=present
      become: yes
      tags: php

    - name: Install Composer
      apt: name=composer state=present
      become: yes
      tags: php

    - name: Install PHP Unit
      apt: name=phpunit state=present
      become: yes
      tags: php
