- hosts: localhost
  tasks:

    - name: Install vim
      apt: name=vim state=present
      become: yes
      tags: utils

    - name: Install CURL
      apt: name=curl state=present
      become: yes
      tags: utils

    - name: Install PHP
      apt: name=php state=present
      become: yes
      tags: php

    - name: Install PHP-CURL
      apt: name=php7.0-curl state=present
      become: yes
      tags: php

    - name: Install Composer
      apt: name=composer state=present
      become: yes
      tags: php

    - name: Install PHP Unit
      apt: name=phpunit state=present
      become: yes
      tags: php

    - name: Install Node
      apt: name=nodejs state=present
      become: yes
      tags: js

    - name: Install npm
      apt: name=npm state=present
      become: yes
      tags: js

    - name: Install Clojure
      apt: name=clojure1.6 state=present
      become: yes
      tags: clj
